openapi: 3.0.3
info:
  title: Mountains Wonders - OpenAPI 3.0
  description: |- 
   Mountains wonders apis
  version: 1.0.0
tags:
  - name: auth
    description: Authentication 
  - name: mountains
    description: Operations about mountains
  - name: refuges
    description: Operations about refuges
paths:
  /auth/currentUser:
    get:
      tags:
        - auth
      summary: Retrieve the currentUser
      description: Retrieve the currentUser
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: user not logged
  /auth/login:
    post:
      tags:
        - auth
      summary: Login 
      description: Login  
      parameters:
        - name: email
          in: query
          description: Email of the user
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: Password of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: invalid credentials
  /auth/register:
    post:
      tags:
        - auth
      summary: Register 
      description: Register a new user
      parameters:
        - name: email
          in: query
          description: Email of the user
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: Password of the user
          required: true
          schema:
            type: string
        - name: name
          in: query
          description: Name of the user
          required: true
          schema:
            type: string
        - name: surname
          in: query
          description: Surname of the user
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Successful operation, user created
        '401':
          description: User with that email already exists
  /auth/logout:
    get:
      tags:
        - auth
      summary: Logout 
      description: Logout from user account
      responses:
        '200':
          description: successful operation
        '401':
          description: invalid credentials
  /mountains/{mountainId}:
    get:
      tags:
        - mountains
      summary: Find mountain by ID
      description: Returns a single mountain
      parameters:
        - name: mountainId
          in: path
          description: ID of mountain to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mountain'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Mountain'   
        '404':
          description: Mountains not found
  /mountains/getMountains:
    get:
      tags:
        - mountains
      summary: Find all mountains
      description: Returns all mountains
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mountain'    
            application/xml:
              schema:
                $ref: '#/components/schemas/Mountain'   
  /mountains/search/{searchString}:
    get:
      tags:
        - mountains
      summary: Find mountains by name
      description: Returns the corrisponding mountains
      parameters:
        - name: searchString
          in: path
          description: Name of the mountains to found
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mountain'    
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mountain'   
        '404':
          description: Mountains not found
components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: giorgio
        email:
          type: string
          format: email
          example: example@gmail.com
        password:
          type: string
        isActive:
          type: boolean
        isAdmin:
          type: boolean
      xml:
        name: order
    Mountain:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
        description:
          type: string
    Refuge:
      type: object
      properties:
        name:
          type: string
        avgRating:
          type: string
        description:
          type: string
        mountainId:
          type: integer
        image:
          type: string
          format: image
        __v:
          type: integer
          example: 1.0 
  #securitySchemes:
    #api_key:
      #type: apiKey
      #name: api_key
      #in: header