swagger: '2.0'
info:
  title: Swagger API
  version: 1.0.0
paths:
  /api/auth/currentUser/route: {}
  /api/auth/login/route: {}
  /api/auth/logout/route: {}
  /api/auth/register/route: {}
  /api/delete/[refugeId]/route: {}
  /api/mountains/route: {}
  /api/mountains/search/route: {}
  /api/mountains/[mountainId]/route: {}
  /api/refuges/route: {}
  /api/refuges/search/route: {}
  /api/refuges/[mountainId]/route: {}
  /api/[mountainId]/addRefuge/route: {}
